
version: "3.8"
services:
  nginx:
    image: yannickvw/coviddashboard_nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
  netapp:
    image: yannickvw/coviddashboard_netapp:latest
    build:
      context: ./netapp/master
    ports:
      - "5000:80"


